Loading plugins default to not from cache
AxFoundation/strax pull request #728
Opened 2023-05-31 02:54 UTC by shenyangshi

Strax is not updating the plugin config when we register an updated plugin with new configs, since it defaults to load from cached plugin lists, the only option was to re-initialize the context.

This is causing confusion for straxen and cutax developers. Given the plugins are not taking many memories, maybe we can just load them again. Strax experts please comment @dachengx @WenzDaniel @JoranAngevaare.

2023-05-31 06:10 UTC, JoranAngevaare commented
Hi @shenyangshi , setting up the caching functionality wasn't entirely trivial: https://github.com/AxFoundation/strax/pull/440, https://github.com/AxFoundation/strax/pull/485, https://github.com/AxFoundation/strax/pull/510, https://github.com/AxFoundation/strax/pull/516 https://github.com/AxFoundation/strax/pull/545, https://github.com/AxFoundation/strax/pull/561 so I can totally believe if there is some edge case not covered (yet).

1. Can you provide a MWE of the issue you are experiencing? 
2. This proposed change is not propagated to other functions, making it virtually impossible to use the cache after this change.
3. Disabling caching will hugely slow down data discovery (like select runs does), you can see the extreme performance loss by setting `use_per_run_defaults==True` in the context config and doing a `st.select_runs`. The cache was introduced precisely for this reason (otherwise, you build the plugin dependency tree for each time you call `st._get_single_plugin`, which is called from `st.select_runs` st.get_*` etc.).
4. I think you can only run into this issue when you don't change [the version of the plugin as well,](https://github.com/AxFoundation/strax/blob/ea28dae8443db2ca883d207e90ff7902723e00ea/strax/context.py#L551), which is probably bad practice since you'd much better use `st.set_config`. Yet, debugging this cache is quite a pain, so perhaps we should come up with something instead of saying "it's bad practice" 😉.
5. I think the easiest solution is to drop the current cache if one does an `st.register`, [maybe somewhere around this line](https://github.com/AxFoundation/strax/blob/ea28dae8443db2ca883d207e90ff7902723e00ea/strax/context.py#L263). you can drop the current cache by setting `st._fixed_plugin_cache=None` (or `self._fixed_plugin_cache=None`, if you add it to the `self.register`).

2023-05-31 06:10 UTC, JoranAngevaare requested changes
Hi @shenyangshi , setting up the caching functionality wasn't entirely trivial: https://github.com/AxFoundation/strax/pull/440, https://github.com/AxFoundation/strax/pull/485, https://github.com/AxFoundation/strax/pull/510, https://github.com/AxFoundation/strax/pull/516 https://github.com/AxFoundation/strax/pull/545, https://github.com/AxFoundation/strax/pull/561 so I can totally believe if there is some edge case not covered (yet).

1. Can you provide a MWE of the issue you are experiencing? 
2. This proposed change is not propagated to other functions, making it virtually impossible to use the cache after this change.
3. Disabling caching will hugely slow down data discovery (like select runs does), you can see the extreme performance loss by setting `use_per_run_defaults==True` in the context config and doing a `st.select_runs`. The cache was introduced precisely for this reason (otherwise, you build the plugin dependency tree for each time you call `st._get_single_plugin`, which is called from `st.select_runs` st.get_*` etc.).
4. I think you can only run into this issue when you don't change [the version of the plugin as well,](https://github.com/AxFoundation/strax/blob/ea28dae8443db2ca883d207e90ff7902723e00ea/strax/context.py#L551), which is probably bad practice since you'd much better use `st.set_config`. Yet, debugging this cache is quite a pain, so perhaps we should come up with something instead of saying "it's bad practice" 😉.
5. I think the easiest solution is to drop the current cache if one does an `st.register`, [maybe somewhere around this line](https://github.com/AxFoundation/strax/blob/ea28dae8443db2ca883d207e90ff7902723e00ea/strax/context.py#L263). you can drop the current cache by setting `st._fixed_plugin_cache=None` (or `self._fixed_plugin_cache=None`, if you add it to the `self.register`).

2023-05-31 07:09 UTC, WenzDaniel commented
Hej Shenyang, thanks for spotting this issue. I second all of Jorans points. I developed a lot of plugins since we introduced the caching and never encountered such an issue. As Joran suggested can you provide an example? In addition, once you have an example can you make first a unittest based on that example which fails the test and then only afterwards add a solution which makes the test pass? I think we should in general enforce this order of making changes.

2023-05-31 07:29 UTC, jmosbacher commented
Hi, I would like to add to Joran and Daniels comments a more general comment. 
The percentage of time strax is used for development of new plugins is a tiny fraction of the time it is used for processing and loading data. 
It is a flawed approach to reduce the performance of every user's usage to save a few minutes during plugin development. The proper implementation of such a change (if indeed deemed to be necessary) would be to have a setting that disables the cache that developers can use during plugin development.
Removing existing features from software is not something to be lightly and especially not when the benefit is only seen by a tiny fraction of its usage.

2023-06-01 13:22 UTC, shenyangshi commented
Thanks everyone for the comments! Here is a MWE: https://github.com/XENONnT/analysiscode/blob/master/misc/example_strax.ipynb

But I realized this PR is not needed, as a much easier way to solve this problem as @JoranAngevaare mentioned, is to update plugin versions while making a change. I'll close this PR then.

2023-06-01 13:23 UTC, closed without merging

2023-06-01 17:55 UTC, JoranAngevaare commented
Hi all, sounds good. Yet I just wanted to point out that option 5 is for free basically. If you set the cache to `None` (during st.register) you will rebuild it the next time anyway. So it won't impact any performance, just less poor PhD students that can't figure out why strax is so stubborn 😄.

But then again, updating the version of the plugin is almost always necessary for strax to prevent loading data with the same lineage. Unless you purposefully use `SaveWhen.NEVER` or something.