Fix caching issue
AxFoundation/strax pull request #768
Opened 2023-10-23 13:16 UTC by WenzDaniel

Fixes issues of plugin caching. Before we only loaded from cache if the target is already cached. If a target is not cached we are initializing all plugins again. This can lead to very long plugin registration times in fuse.

2023-10-23 15:14 UTC, WenzDaniel commented
Maybe some additional explanation: 
* I moved the code from the local get_plugin function into the new `__get_plugin` method.
* The dictionary which contains the list of plugins returned by _get_plugins is now created more explicitly than the old non_local_plugins dict.
* For cleanliness I moved the lineage definition into its own function.

2023-11-13 16:20 UTC, dachengx requested changes
Thanks @WenzDaniel . The cleaning looks cool. I am still testing the PR to see any potential lineage change, but the comment is below.

2023-11-17 09:48 UTC, WenzDaniel commented
Somehow I was just unable to find raw recrods aqmon and aqmon nv. When using this branch... need to check why first

2023-11-20 12:21 UTC, HenningSE commented
Thanks for the work Daniel! I'm wondering if we can still increase the speed somehow. When working with fuse and also registering cuts strax still needs about 2-10 minutes to figure out how to load the requested cut data.

2023-11-21 09:47 UTC, WenzDaniel commented
Fixed lineage change of raw records with https://github.com/AxFoundation/strax/pull/775

2023-11-21 10:10 UTC, WenzDaniel commented on strax/context.py
> +        while targets and counter < 100:
@dachengx I increased the safety counter to 10_000 and added a raise condition if not all targest are initialized.

2023-11-21 10:13 UTC, WenzDaniel commented
I guess we can ignore the complex method issue of codefactor I am not going to change that.

2023-11-21 13:40 UTC, dachengx approved these changes
Thanks @WenzDaniel .

2023-11-21 13:58 UTC, merged